#version: '3.8'
#services:
#  app:
#    image: postgres
#    ports:
#      - "8085:8085"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5433/msachatdb
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=Hc20070521
#    depends_on:
#      - db
#  db:
#    image: postgres:latest
#    environment:
#      POSTGRES_DB: msachatdb
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: Hc20070521
#    ports:
#      - "5433:5433"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#volumes:
#  postgres_data:
version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Hc20070521
      - POSTGRES_DB=msachatdb
    ports:
      - '5433:5433'

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8085:8085'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db/msachatdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Hc20070521
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db