version: '3.8'

services:
  app:
    # 这里的镜像名是自定义的，所以需要 build 参数
    # 否则 docker 会从 docker hub 获取
    # 然而官方并没有这个镜像，就会报错
    image: msa-chat-backend:v1
    build: .
    # SpringBoot 运行时需要数据库服务先启动
    depends_on:
      - db
    ports:
      - 8085:8085
    environment:
      # 这里不能用 localhost 访问数据库
      # 因为两个容器之间不是局域网环境，不能用 localhost 访问
      # 但是 docker 之间可以直接获取地址，用服务名访问即可
      # 这里就是通过 <服务名:端口> 来访问数据库
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/msa_chat
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect

  db:
    # 这里的镜像名采用官方 postgres 镜像，就不用自己配置了
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=msa_chat
    ports:
      - 5432:5432