version: '3.8'
services:
  app:
    image: sttt329/msa-chat:backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/msachatdb
      - SPRING_DATASOURCE_USERNAME=msachat
      - SPRING_DATASOURCE_PASSWORD= 000000
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: msachatdb
      POSTGRES_USER: msachat
      POSTGRES_PASSWORD: 000000
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: