version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - my_data:/var/lib/postgresql/data
volumes:
  my_data:
